baseurl = "https://amirrezaghaderi.com/fa/"
languageCode = "fa-IR"
title = "امیررضا قادری"
Paginate = 30
publishdir = "../amirrezaghaderi.com/fa"
disqusShortname = "amirrezaghaderi-ir"

pygmentsUseClasses = true
pygmentsCodeFences = true

[indexes]
tag = "topic"
