baseurl = "https://amirrezaghaderi.ir/"
languageCode = "fa-IR"
title = "امیررضا قادری"
Paginate = 30
disqusShortname = "amirrezaghaderi-ir"

pygmentsUseClasses = true
pygmentsCodeFences = true

[indexes]
tag = "topic"
